# Generated by Django 5.1.7 on 2025-03-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="source",
            field=models.CharField(default="manual", max_length=10),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arriving_flights",
                to="flights.airport",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departing_flights",
                to="flights.airport",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(default="unknown", max_length=20),
        ),
    ]
